### ISSUE TITLE
Connection closed Error

### ISSUE THREAD

**Issue by jordankothe9** [jordankothe9/CIS499#2]
When running on the same machine as the database / linux this error is thrown. It is not thrown in the ide or on windows

Does throw the error on any linux machine?

Mar 25, 2021 11:58:01 AM parksmartdatabaseconnector.ParkSmartDatabaseConnector proccessVehicleSTR
SEVERE: null
com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:190)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:388)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareStatement(SQLServerConnection.java:2166)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareStatement(SQLServerConnection.java:1853)
        at parksmartdatabaseconnector.SQLconnection.plateexists(SQLconnection.java:107)
        at parksmartdatabaseconnector.SQLconnection.addVehicle(SQLconnection.java:85)
        at parksmartdatabaseconnector.ParkSmartDatabaseConnector.proccessVehicleSTR(ParkSmartDatabaseConnector.java:121)
        at parksmartdatabaseconnector.ParkSmartDatabaseConnector.main(ParkSmartDatabaseConnector.java:69)

com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:190)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:388)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareStatement(SQLServerConnection.java:2166)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareStatement(SQLServerConnection.java:1853)
        at parksmartdatabaseconnector.SQLconnection.plateexists(SQLconnection.java:107)
        at parksmartdatabaseconnector.SQLconnection.addVehicle(SQLconnection.java:85)
        at parksmartdatabaseconnector.ParkSmartDatabaseConnector.proccessVehicleSTR(ParkSmartDatabaseConnector.java:121)
        at parksmartdatabaseconnector.ParkSmartDatabaseConnector.main(ParkSmartDatabaseConnector.java:69)

**Comment by jordankothe9** [comment]
After getting the error the program continues and doesn't change the sql database. The error happens most of the time but not always

**Comment by jordankothe9** [comment]
Doesn't happen on other linux machines

**Comment by jordankothe9** [comment]
It appears that restarting the mssql database fixed the issue

systemctl restart mssql-server
