### ISSUE TITLE
Number Format issue

### ISSUE THREAD

**Issue by jordankothe9** [jordankothe9/CIS499#3]
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.valueOf(Integer.java:766)
        at parksmartdatabaseconnector.ParkSmartDatabaseConnector.main(ParkSmartDatabaseConnector.java:50)

**Comment by jordankothe9** [comment]
This error is caused by a properties file that is not setup yet

**Comment by jordankothe9** [comment]
FIxed issue by adding a check to see if the config file has been setup
